### ISSUE TITLE
FFT fails on Signal2Ds

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#112] opened 2017-02-21 14:32 UTC
As the title says. Terminal returns the following error:

```python
s = hs.signals.Signal2D(sc.misc.face()).as_signal2D((2,0)).inav[0]
s.plot()
# Call the FFT function from the menu
```

Error: 
```
Traceback (most recent call last):
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/plugins/fft.py", line 167, in fft
    for i in do_ffts():
  File "/Users/thomas/Dropbox/0_Git/hyperspyUI/hyperspyui/plugins/fft.py", line 149, in do_ffts
    if u.endswith('-1'):
AttributeError: '_Undefined' object has no attribute 'endswith'
```

**Comment by vidartf** [comment] 2017-02-21 14:44
Duplicate of #95.

**Closed by vidartf** 2017-02-21 14:44 UTC

**Comment by thomasaarholt** [comment] 2017-02-21 14:47
Sorry, should have searched. Thought I was up to date on the issues.
