### ISSUE TITLE
UI with HyperspyDev

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspyUI#81] opened 2016-12-07 15:00 UTC
The UI doesn't work with the developer version of hyperspy, because it looks for version "1.1.1", whilst the dev version is "1.1.1+dev". Is there a quick solution to fixing this? Would removing the hyperspy requirement in the setup.py file fix it? Or can we change it? (My compiler, xcode - 10GB is currently uninstalled, and I have a small SSD...), so Id rather only install it if you think it would work.

**Comment by vidartf** [comment] 2016-12-07 22:17
If you locally change hyperspy's version to '1.1.1+dev0', does it work (c.f. https://www.python.org/dev/peps/pep-0440/#developmental-releases)?

**Comment by vidartf** [comment] 2016-12-07 22:19
Also c.f. https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions .

**Comment by vidartf** [comment] 2016-12-07 22:20
Related to that last link, have you tried with the `--pre` flag?

**Comment by thomasaarholt** [comment] 2016-12-07 22:40
I just removed the requirement of hyperspy beig installed in the setup.py,
and that worked fine. There's gotta be a way to handle this though? It has
to be a common problem.

**Comment by vidartf** [comment] 2016-12-07 22:45
I think the problem is that newer versions of pip won't allow dev version without the `--pre` flag.

**Comment by vidartf** [comment] 2017-01-10 11:37
@thomasaarholt I can't really seem to reproduce this error. Could you list the commands you run to install hyperspy/ui, and where it goes wrong?

**Comment by thomasaarholt** [comment] 2017-01-10 11:58
I install hyperspy by `pip install -e path/to/hyperspy_fork_from_master`, and then ui by `pip install -e path/to/hyperspyui_fork_from_master`. 

I can't check right now by uninstalling/reinstalling, but I think the problem is that installing the UI makes it look for a "stable" install of hyperspy which it doesn't find. So the problem occurs with the second step.

**Comment by vidartf** [comment] 2017-01-10 12:28
HyperspyUI lists requirements as `hyperspy >= 1.1.1`. If the dev version string does not satisfy this, I would argue the hyperspy version string is wrong (see above). @francisco-dlp do you have any input on this?

A workaround for now is to simply reinstall the dev version of hyperspy after installing the UI, e.g.
```
pip install -e path/to/hyperspy_fork_from_master
pip install -e path/to/hyperspyui_fork_from_master
pip install -e path/to/hyperspy_fork_from_master
```

**Comment by vidartf** [comment] 2017-01-23 17:20
Closing, as I cannot see that this is an issue with how the UI is set up.

**Closed by vidartf** 2017-01-23 17:20 UTC
